//////////////////////////////// TEMPORARY

bool STATION_ALTERED = false;
bool SETTINGS_ALTERED = false;

bool PCF8574_RELAY_1_STATE;
bool PCF8574_RELAY_2_STATE;
bool PCF8574_RELAY_3_STATE;
bool PCF8574_RELAY_TEMP_STATE;
uint8_t PCF8574_READINGS_BUTTONS_LAST = 0;
uint16_t PCF8574_READINGS_BUTTONS_TURNS = 0;
uint8_t PCF8574_READINGS_RELAYS_LAST = 0;
    
//////////////////////////////// STRUCTS

struct STRUCT_STATION {

  uint32_t TIMESTAMP = 0;

  uint32_t ACTIVATION;
  uint32_t EXPIRATION;
  bool ACTIVE = false;
  
} STATION;

struct STRUCT_CUSTOMER {

  uint32_t TIMESTAMP = 0;
  
  char ID[11];
  char NAME[32];
  char FNAME[32];
  char TELEPHONE[12];
  char MOBILE[12];
  char CITY[32];
  char ADDRESS[128];
  char ZIP[11];
  
} CUSTOMER;

struct STRUCT_SETTINGS {

  uint32_t TIMESTAMP = 0;

  
  char NAME[32];

  bool RGB_LED_STATE;
  uint8_t RGB_LED_TRESHHOLD;
  uint8_t RGB_LED_DAY_MODE;
  uint32_t RGB_LED_DAY_COLOR;
  uint8_t RGB_LED_NIGHT_MODE;
  uint32_t RGB_LED_NIGHT_COLOR;

  bool RGB_LAMP_STATE;
  uint8_t RGB_LAMP_TRESHHOLD;
  uint8_t RGB_LAMP_DAY_MODE;
  uint32_t RGB_LAMP_DAY_COLOR;
  uint8_t RGB_LAMP_NIGHT_MODE;
  uint32_t RGB_LAMP_NIGHT_COLOR;

  char WIFI_SSID[32];
  char WIFI_PASSWORD[32]; 
  bool WIFI_DHCP = false;
  IPAddress WIFI_IP;
  IPAddress WIFI_GATE;
  IPAddress WIFI_MASK;

  char RELAY_1_NAME[32];
  uint8_t RELAY_1_MODE;
  bool RELAY_1_MODE_0_STATE;
  bool RELAY_1_MODE_1_ENABLE[10];
  uint32_t RELAY_1_MODE_1_ACTIVATE;
  uint32_t RELAY_1_MODE_1_DEACTIVATE;
  uint32_t RELAY_1_MODE_1_ON[10];
  uint32_t RELAY_1_MODE_1_OFF[10];
  uint32_t RELAY_1_MODE_2_ACTIVATE;
  uint32_t RELAY_1_MODE_2_DEACTIVATE;
  uint32_t RELAY_1_MODE_2_DURATION;
  uint32_t RELAY_1_MODE_2_INTERVAL;
  uint16_t RELAY_1_MODE_2_COUNT;
  uint16_t RELAY_1_MODE_2_COUNT_ELAPSED;

  char RELAY_2_NAME[32];
  uint8_t RELAY_2_MODE;
  bool RELAY_2_MODE_0_STATE;
  bool RELAY_2_MODE_1_ENABLE[10];
  uint32_t RELAY_2_MODE_1_ACTIVATE;
  uint32_t RELAY_2_MODE_1_DEACTIVATE;
  uint32_t RELAY_2_MODE_1_ON[10];
  uint32_t RELAY_2_MODE_1_OFF[10];
  uint32_t RELAY_2_MODE_2_ACTIVATE;
  uint32_t RELAY_2_MODE_2_DEACTIVATE;
  uint32_t RELAY_2_MODE_2_DURATION;
  uint32_t RELAY_2_MODE_2_INTERVAL;
  uint16_t RELAY_2_MODE_2_COUNT;
  uint16_t RELAY_2_MODE_2_COUNT_ELAPSED;

  char RELAY_3_NAME[32];
  uint8_t RELAY_3_MODE;
  bool RELAY_3_MODE_0_STATE;
  bool RELAY_3_MODE_1_ENABLE[10];
  uint32_t RELAY_3_MODE_1_ACTIVATE;
  uint32_t RELAY_3_MODE_1_DEACTIVATE;
  uint32_t RELAY_3_MODE_1_ON[10];
  uint32_t RELAY_3_MODE_1_OFF[10];
  uint32_t RELAY_3_MODE_2_ACTIVATE;
  uint32_t RELAY_3_MODE_2_DEACTIVATE;
  uint32_t RELAY_3_MODE_2_DURATION;
  uint32_t RELAY_3_MODE_2_INTERVAL;
  uint16_t RELAY_3_MODE_2_COUNT;
  uint16_t RELAY_3_MODE_2_COUNT_ELAPSED;

  uint8_t RELAY_TEMP_MODE;
  bool RELAY_TEMP_MODE_0_STATE;

  bool TEMP_AUTO;
  float TEMP_TRESHHOLD;
  bool TEMP_ECO;
  bool DS18B20_TEMP_INVERT;
  
  bool FEED_AUTO;
  bool FEED_MODE;
  uint32_t FEED_TIME;
  uint32_t FEED_INTERVAL;

} SETTINGS;
